# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3965db1f1ada0002a5d014e5776f74f196fe8b6e3c6a7f2410c5b6f2f3ebbcfbd21b0fc9e5a756736eb7919669e12690e7e3edbd81e604f3796e3e5bd6287021

test:
  secret_key_base: be1b090b00b485be02a3d727a4eba8b7645e309175d06ea7d0fddd8bfd81d61e6de6e06f8c0a4886409ae0c2a913a70f8393145d9c813914cd972606244a9fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
